//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Belgo.Dados.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAD_PARTICIPACAO> CAD_PARTICIPACAO { get; set; }
        public virtual DbSet<CAD_PERGUNTA> CAD_PERGUNTA { get; set; }
        public virtual DbSet<CAD_PESQUISA> CAD_PESQUISA { get; set; }
        public virtual DbSet<CAD_RESPOSTA> CAD_RESPOSTA { get; set; }
        public virtual DbSet<SCA_USUARIO> SCA_USUARIO { get; set; }
    }
}
