//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Belgo.Dados.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAD_PESQUISA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAD_PESQUISA()
        {
            this.CAD_PERGUNTA = new HashSet<CAD_PERGUNTA>();
        }
    
        public long COD_PESQUISA { get; set; }
        public string NOM_PESQUISA { get; set; }
        public Nullable<bool> IND_FECHADO { get; set; }
        public Nullable<long> COD_USER_CRIACAO { get; set; }
        public Nullable<System.DateTime> DTA_CRIACAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAD_PERGUNTA> CAD_PERGUNTA { get; set; }
        public virtual SCA_USUARIO SCA_USUARIO { get; set; }
    }
}
