//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Belgo.Dados.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAD_PERGUNTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAD_PERGUNTA()
        {
            this.CAD_PARTICIPACAO = new HashSet<CAD_PARTICIPACAO>();
            this.CAD_RESPOSTA = new HashSet<CAD_RESPOSTA>();
        }
    
        public long COD_PERGUNTA { get; set; }
        public long COD_PESQUISA { get; set; }
        public string DSC_PERGUNTA { get; set; }
        public string IND_TPO_PERGUNTA { get; set; }
        public Nullable<int> NUM_ORDEM_PERGUNTA { get; set; }
        public Nullable<long> COD_USER_CRIACAO { get; set; }
        public Nullable<System.DateTime> DTA_CRIACAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAD_PARTICIPACAO> CAD_PARTICIPACAO { get; set; }
        public virtual CAD_PESQUISA CAD_PESQUISA { get; set; }
        public virtual SCA_USUARIO SCA_USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAD_RESPOSTA> CAD_RESPOSTA { get; set; }
    }
}
