//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Belgo.Dados.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCA_USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCA_USUARIO()
        {
            this.CAD_PERGUNTA = new HashSet<CAD_PERGUNTA>();
            this.CAD_PESQUISA = new HashSet<CAD_PESQUISA>();
            this.CAD_RESPOSTA = new HashSet<CAD_RESPOSTA>();
        }
    
        public long COD_USUARIO { get; set; }
        public string NOM_USUARIO { get; set; }
        public string DSC_EMAIL { get; set; }
        public string PSW_SENHA { get; set; }
        public string IND_EXCLUIDO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAD_PERGUNTA> CAD_PERGUNTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAD_PESQUISA> CAD_PESQUISA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAD_RESPOSTA> CAD_RESPOSTA { get; set; }
    }
}
